name:  maven ile java build push

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Kodu check
      uses: actions/checkout@v3

    - name: Java kur
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Maven ile derle
      run: mvn clean package -DskipTests

    - name: Docker Hub'a giriş yap
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker image oluştur
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .

    - name: Docker image push et
      run: docker push ${{ secrets.DOCKER_USERNAME }}/myjavaproject:latest
